baseurl = "http://r-gators.netlify.com/"
title = "R-Gators"
languageCode = "en-us"
paginate = "6" # Number of posts per page
theme = "Mainroad"
disqusShortname = "r-gators" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-75169517-2" # Enable Google Analytics by entering your tracking id

[Author]
    name = "R-Gators"
    bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
    avatar = "img/avatar.png"


[Params]
    subtitle = "Activity hub for R programming at the University of Florida" # Subtitle of your site
    description = " John Doe's Personal blog about everything" # Description of your site
    opengraph = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = true # Move sidebar to the left side if true
    authorbox = false
    post_navigation = false
    postSections = ["post"]


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
    social = true # Enable "Social" widget
    social_github = "ufrmeetup"
    social_email = "R-USERS-L@LISTS.UFL.EDU"