baseurl = "http://r-gators.netlify.com/"
title = "R-Gators"
languageCode = "en-us"
paginate = "6" # Number of posts per page
theme = "Mainroad"
disqusShortname = "r-gators" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-75169517-2" # Enable Google Analytics by entering your tracking id
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[Author]
    name = "R-Gators"
    bio = "Activity hub for R programming at the University of Florida."
    avatar = ""


[Params]
    subtitle = "Activity hub for R programming at the University of Florida" # Subtitle of your site
    description = " Activity hub for R programming at the University of Florida" # Description of your site
    opengraph = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = true # Move sidebar to the left side if true
    authorbox = false
    post_navigation = false
    postSections = ["post"]


[Params.widgets]
    search = false # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
    social = true # Enable "Social" widget
    social_github = "ufrmeetup"
    social_facebook = "groups/270528976467287/"
    social_email = "R-USERS-L@LISTS.UFL.EDU"